### ISSUE TITLE
bangbang运行错误

### ISSUE THREAD

**Issue by zhaoboy9692** [sledgeh4w/chomper#102]
[ddddd](http://zhaoxincheng.com/wp-content/uploads/2024/11/ddddd.zip)
     encrypt_str = '111111111'
        encrypt_result = objc.msg_send("BangSafeSDK", "checkcode:dataStyle:", pyobj2nsobj(emu, encrypt_str), 2)
        logger.info("Encrypt result: %s", emu.read_string(objc.msg_send(encrypt_result, "cStringUsingEncoding:", 4)))
        # Decrypt
        decrypt_str = encrypt_result
        decrypt_result = objc.msg_send("BangSafeSDK", "decheckcode:", pyobj2nsobj(emu, decrypt_str))
        logger.info("Decrypt result: %s", emu.read_string(objc.msg_send(decrypt_result, "cStringUsingEncoding:", 4)))

2024-11-29 21:23:09,925 - chomper.file - INFO: stat called: path='/var/containers/Bundle/Application/2212A6A9-72D5-4376-8E78-D1371F62D43A'
2024-11-29 21:23:09,936 - chomper.core - ERROR: Emulator crashed from: libsystem_kernel.dylib!0x1ac32e2f0 -> libsystem_kernel.dylib!0x1ac313794 -> Foundation!0x181728b94 -> Foundation!0x18160c0e0 -> Foundation!0x18160bc98 -> ddddd!0x103c98588 -> ddddd!0x103c7e450 -> ddddd!0x103c93c0c -> ddddd!0x103c938b0
2024-11-29 21:23:09,936 - chomper.core - INFO: Call symbol "_objc_autoreleasePoolPop"
2024-11-29 21:23:09,936 - chomper.core - INFO: Start emulate at libobjc.A.dylib!0x19480f380
Traceback (most recent call last):
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/agent/testcomper/example_ios_bangbang.py", line 65, in <module>
    main()
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/agent/testcomper/example_ios_bangbang.py", line 56, in main
    encrypt_result = objc.msg_send("BangSafeSDK", "checkcode:dataStyle:", pyobj2nsobj(emu, encrypt_str), 2)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/objc.py", line 55, in msg_send
    return self.emu.call_symbol("_objc_msgSend", receiver, sel, *new_args)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/core.py", line 730, in call_symbol
    return self._start_emulate(address, *args)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/core.py", line 212, in _start_emulate
    self.uc.emu_start(address, stop_addr)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/unicorn/unicorn_py3/unicorn.py", line 771, in emu_start
    raise self._hook_exception
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/unicorn/unicorn_py3/unicorn.py", line 365, in wrapper
    return func(uc, *args, **kwargs)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/unicorn/unicorn_py3/unicorn.py", line 1052, in __hook_intr_cb
    callback(uc, intno, user_data)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/core.py", line 407, in _interrupt_callback
    self._dispatch_syscall()
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/core.py", line 436, in _dispatch_syscall
    self.crash("Unhandled system call")
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/core.py", line 360, in crash
    raise EmulatorCrashedException(
chomper.exceptions.EmulatorCrashedException: Unhandled system call at libsystem_kernel.dylib!0x1ac32e2f0
x86/m3 基本都会有这个错误。

**Comment by sledgeh4w** [comment]
可以提供下这个二进制文件吗？

**Comment by zhaoboy9692** [comment]
> 可以提供下这个二进制文件吗？

[这个](http://zhaoxincheng.com/wp-content/uploads/2024/11/ddddd.zip)

**Comment by sledgeh4w** [comment]
在 sub_103C984A4 这个函数中，它尝试读取 Info.plist 中的 CFBundleIdentifier 并与 com.byd.BYDi 比较，然后返回结果（其实就是一个包名校验）。chomper 还没有直接从底层支持 Info.plist 的读取，所以就报错了。

最简单的解决方案就是 hook 掉 sub_103C984A4 函数，并让它直接返回 1，跳过文件的读取。

```
def hook_retval(retval):
    def decorator(emu, *args):
        return retval

    return decorator

emu.add_interceptor(binary.base + 0x103C984A4, hook_retval(1))
```

**Comment by zhaoboy9692** [comment]
> 在 sub_103C984A4 这个函数中，它尝试读取 Info.plist 中的 CFBundleIdentifier 并与 com.byd.BYDi 比较，然后返回结果（其实就是一个包名校验）。chomper 还没有直接从底层支持 Info.plist 的读取，所以就报错了。
> 
> 最简单的解决方案就是 hook 掉 sub_103C984A4 函数，并让它直接返回 1，跳过文件的读取。
> 
> ```
> def hook_retval(retval):
>     def decorator(emu, *args):
>         return retval
> 
>     return decorator
> 
> emu.add_interceptor(binary.base + 0x103C984A4, hook_retval(1))
> ```

ok 感谢  支持这个项目

**Comment by zhaoboy9692** [comment]
close
