### ISSUE TITLE
再ios-hooks里面增加代码 会crash

### ISSUE THREAD

**Issue by zhaoboy9692** [sledgeh4w/chomper#103]
还是之前dddd
新增代码
@register_hook("_CFUUIDCreateString")
def hook_CFUUIDCreateString(uc, address, size, user_data):
    emu = user_data["emu"]
    uuids = "EF6D755E-6FC6-4883-872D-D4BDD4EDD9C7"
    str_ptr = pyobj2nsobj(emu, uuids)
    return str_ptr
函数调用完毕，退出的时候会崩溃
2024-12-03 12:46:26,066 - chomper.core - INFO: Start emulate at libobjc.A.dylib!0x1947ec460
2024-12-03 12:46:26,066 - __main__ - INFO: Decrypt result: 解密结果
2024-12-03 12:46:26,066 - chomper.core - INFO: Call symbol "_objc_autoreleasePoolPop"
2024-12-03 12:46:26,066 - chomper.core - INFO: Start emulate at libobjc.A.dylib!0x19480f380
2024-12-03 12:46:26,067 - chomper.core - ERROR: Emulator crashed from: CoreFoundation!0x1804d9218 -> CoreFoundation!0x1804d920c -> CoreFoundation!0x1803ef838 -> libobjc.A.dylib!0x19480f570 -> libobjc.A.dylib!0x19480f44c
Traceback (most recent call last):
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/agent/testcomper/example_ios_bangbang.py", line 98, in <module>
    main()
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/agent/testcomper/example_ios_bangbang.py", line 93, in main
    logger.info("Decrypt result: %s",
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/objc.py", line 73, in autorelease_pool
    self.emu.call_symbol("_objc_autoreleasePoolPop", context)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/core.py", line 727, in call_symbol
    return self._start_emulate(address, *args)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/core.py", line 212, in _start_emulate
    self.uc.emu_start(address, stop_addr)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/unicorn/unicorn_py3/unicorn.py", line 771, in emu_start
    raise self._hook_exception
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/unicorn/unicorn_py3/unicorn.py", line 365, in wrapper
    return func(uc, *args, **kwargs)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/unicorn/unicorn_py3/unicorn.py", line 1052, in __hook_intr_cb
    callback(uc, intno, user_data)
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/core.py", line 421, in _interrupt_callback
    self.crash(f"Unhandled interruption {intno}")
  File "/Users/didi/Documents/PycharmProjects/frida-agent-example/.venv/lib/python3.9/site-packages/chomper/core.py", line 360, in crash
    raise EmulatorCrashedException(
chomper.exceptions.EmulatorCrashedException: Unhandled interruption 7 at CoreFoundation!0x1804d9218
这样的其实也会发生同样的crash <img width="906" alt="image" src="https://github.com/user-attachments/assets/319cddab-e282-4673-9ae4-3a9e9879edee">

**Comment by sledgeh4w** [comment]
在 `objc.autorelease_pool()` 这个上下文退出时会触发OC的垃圾回收，崩溃是在这里发生的。

对于第一种写法，应该是返回了不正确的对象类型导致，正常应该返回CF对象，这里你用了`pyobj2nsobj`，我测试了用`pyobj2cfobj`不会报错。

对于第二种写法，不应该返回一个固定的对象，而是应该根据调用动态创建一个对象。因为如果这个函数如果本来应该创建一个新的对象返回，但是程序在多次调用时一直返回同一个对象，那么会让OC运行时在垃圾回收时错误地对这个对象进行多次释放，就会导致崩溃。

```python
def hook_cf_uuid_create_string(uc, address, size, user_data):
    cf_uuid = emu.call_symbol("_CFUUIDCreate", 0)
    cf_uuid_str = emu.call_symbol("_CFUUIDCreateString", 0, cf_uuid)
    return cf_uuid_str

cf_uuid_create_string_addr = emu.find_symbol("_CFUUIDCreateString").address
emu.add_interceptor(cf_uuid_create_string_addr, hook_cf_uuid_create_string)
```

**Comment by zhaoboy9692** [comment]
> 在 `objc.autorelease_pool()` 这个上下文退出时会触发OC的垃圾回收，崩溃是在这里发生的。
> 
> 对于第一种写法，应该是返回了不正确的对象类型导致，正常应该返回CF对象，这里你用了`pyobj2nsobj`，我测试了用`pyobj2cfobj`不会报错。
> 
> 对于第二种写法，不应该返回一个固定的对象，而是应该根据调用动态创建一个对象。因为如果这个函数如果本来应该创建一个新的对象返回，但是程序在多次调用时一直返回同一个对象，那么会让OC运行时在垃圾回收时错误地对这个对象进行多次释放，就会导致崩溃。
> 
> ```python
> def hook_cf_uuid_create_string(uc, address, size, user_data):
>     cf_uuid = emu.call_symbol("_CFUUIDCreate", 0)
>     cf_uuid_str = emu.call_symbol("_CFUUIDCreateString", 0, cf_uuid)
>     return cf_uuid_str
> 
> cf_uuid_create_string_addr = emu.find_symbol("_CFUUIDCreateString").address
> emu.add_interceptor(cf_uuid_create_string_addr, hook_cf_uuid_create_string)
> ```

果然  用pyobj2cfobj可以，早上试了一下 估计没注意到跑通了，后边分析了下用cf对象，就想这直接调用_CFUUIDCreateString 返回固定的uuid，地址都是相同的，想着oc应该不会回收， 目的是固定uuid，感谢大佬
