### ISSUE TITLE
示例报错，自己写的也是这个错误

### ISSUE THREAD

**Issue by yynewbee** [sledgeh4w/chomper#114]
Traceback (most recent call last):
  File "D:\python3.11.4\Lib\site-packages\chomper\core.py", line 210, in _start_emulate
    self.uc.emu_start(address, stop_addr)
  File "D:\python3.11.4\Lib\site-packages\unicorn\unicorn.py", line 548, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\NPC-277\Downloads\chomper-main (1)\chomper-main\examples\example_ios_zhihu.py", line 102, in <module>
    main()
  File "C:\Users\NPC-277\Downloads\chomper-main (1)\chomper-main\examples\example_ios_zhihu.py", line 66, in main
    result = objc.msg_send(
             ^^^^^^^^^^^^^^
  File "D:\python3.11.4\Lib\site-packages\chomper\objc.py", line 58, in msg_send
    return self.emu.call_symbol("_objc_msgSend", receiver, sel, *new_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python3.11.4\Lib\site-packages\chomper\core.py", line 758, in call_symbol
    return self._start_emulate(address, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python3.11.4\Lib\site-packages\chomper\core.py", line 215, in _start_emulate
    self.crash("Unknown reason", from_exc=e)
  File "D:\python3.11.4\Lib\site-packages\chomper\core.py", line 381, in crash
    raise EmulatorCrashedException(message) from from_exc
chomper.exceptions.EmulatorCrashedException: Unknown reason at libsystem_kernel.dylib!0x1ac308638

**Comment by sledgeh4w** [comment]
你的 chomper 好像不是最新版本，可以更新一下版本再试试
