### ISSUE TITLE
No memory available or memory not present (UC_ERR_NOMEM)

### ISSUE THREAD

**Issue by killed** [sledgeh4w/chomper#93]
All examples keep throwing the same error and any binaries I try also throw the same

My box is `Ubuntu 22.04.4` `x86_64`

```
2024-10-18 22:09:46,437 - __main__ - INFO: Load module "CSMBP-AppStore-Package"
Traceback (most recent call last):
  File "/home/whatever/chomper/test.py", line 60, in <module>
    main()
  File "/home/whatever/chomper/test.py", line 37, in main
    czair = emu.load_module(
  File "/usr/local/lib/python3.10/dist-packages/chomper/core.py", line 516, in load_module
    module = self.os.loader.load(
  File "/usr/local/lib/python3.10/dist-packages/chomper/os/ios/loader.py", line 235, in load
    size = self._map_segments(binary, module_base)
  File "/usr/local/lib/python3.10/dist-packages/chomper/os/ios/loader.py", line 28, in _map_segments
    self.emu.uc.mem_map(map_addr, map_size)
  File "/usr/local/lib/python3.10/dist-packages/unicorn/unicorn.py", line 621, in mem_map
    raise UcError(status)
unicorn.unicorn.UcError: No memory available or memory not present (UC_ERR_NOMEM)
```

**Comment by sledgeh4w** [comment]
Thanks for your report, fixed in #94
