### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'bindings'

### ISSUE THREAD

**Issue by killed** [sledgeh4w/chomper#95]
```
Traceback (most recent call last):
  File "/home/whatever/chomper/test.py", line 49, in <module>
    main()
  File "/home/whatever/chomper/test.py", line 44, in main
    libraryModule = emulator.load_module("data/apps/test/Test")
  File "/usr/local/lib/python3.10/dist-packages/chomper/core.py", line 516, in load_module
    module = self.os.loader.load(
  File "/usr/local/lib/python3.10/dist-packages/chomper/os/ios/loader.py", line 240, in load
    lazy_bindings = self._process_relocation(binary, module_base, symbols)
  File "/usr/local/lib/python3.10/dist-packages/chomper/os/ios/loader.py", line 203, in _process_relocation
    return self._process_symbol_relocation(binary, module_base, symbols)
  File "/usr/local/lib/python3.10/dist-packages/chomper/os/ios/loader.py", line 120, in _process_symbol_relocation
    for binding in binary.dyld_info.bindings:
AttributeError: 'NoneType' object has no attribute 'bindings'
```

`binary.dyld_info` is returning None

**Comment by sledgeh4w** [comment]
It seems that there are problems with this binary file. How did you get it?

**Comment by killed** [comment]
Apologies about that, unsure what happened i pulled from device again and it seems to be fine now
