### ISSUE TITLE
对继承UIViewController的类进行alloc init会报错. 对继承NSObject的类进行初始化alloc init没问题

### ISSUE THREAD

**Issue by ljy0jy** [sledgeh4w/chomper#98]
result3 = objc.msg_send("NewVcViewController", "alloc")
        NewVcViewController = objc.msg_send(result3,"init")

<<NewVcViewController.h>>
@interface NewVcViewController : UIViewController
-(int)simpleTest:(int)a add:(int)b;

+(int)simpleTest_class:(int)a add:(int)b;
@end

<<NewVcViewController.m>>
#import "NewVcViewController.h"

@interface NewVcViewController ()

@end

@implementation NewVcViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}

-(int)simpleTest:(int)a add:(int)b{
    return a+b;
}
+(int)simpleTest_class:(int)a add:(int)b {
    return a+b;
}

Traceback (most recent call last):
  File "/Users/new/Documents/pythonProject/iosRe/.venv/lib/python3.12/site-packages/chomper/core.py", line 207, in _start_emulate
    self.uc.emu_start(address, stop_addr)
  File "/Users/new/Documents/pythonProject/iosRe/.venv/lib/python3.12/site-packages/unicorn/unicorn_py3/unicorn.py", line 642, in emu_start
    raise UcError(status)
unicorn.unicorn_py3.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/new/Documents/learn/iOS逆向/chomper_code/chomper/examples/ios_te.py", line 62, in <module>
    main()
  File "/Users/new/Documents/learn/iOS逆向/chomper_code/chomper/examples/ios_te.py", line 51, in main
    NewVcViewController = objc.msg_send(result3,"init")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/new/Documents/pythonProject/iosRe/.venv/lib/python3.12/site-packages/chomper/objc.py", line 55, in msg_send
    return self.emu.call_symbol("_objc_msgSend", receiver, sel, *new_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/new/Documents/pythonProject/iosRe/.venv/lib/python3.12/site-packages/chomper/core.py", line 723, in call_symbol
    return self._start_emulate(address, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/new/Documents/pythonProject/iosRe/.venv/lib/python3.12/site-packages/chomper/core.py", line 210, in _start_emulate
    self.crash("Unknown reason", exc=e)
  File "/Users/new/Documents/pythonProject/iosRe/.venv/lib/python3.12/site-packages/chomper/core.py", line 355, in crash
    raise EmulatorCrashedException(
chomper.exceptions.EmulatorCrashedException: Unknown reason at libcorecrypto.dylib!0x1c426a4d8
nanobind: leaked 22 instances!

**Comment by sledgeh4w** [comment]
chomper 主要用来模拟执行加解密那种偏计算的程序，并没有支持所有的 OC 类或者其他一些环境，尤其是像这种 UI 相关的类是不支持的。
